name: Copy File to Target Repositories

on:
  workflow_dispatch:  # You can trigger this workflow manually

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: mhd8a/git-demo  # Replace with the source repository information

    - name: List files in source repo
      run: |
        source_file="/mhd8a/git-demo/new_year.cpp"  # Specify the source file path
        if [ -f "$source_file" ]; then
          echo "Source file $source_file exists."
        else
          echo "Source file $source_file does not exist."
          exit 1
        fi

    - name: Check and copy to target repos
      run: |
        source_file="new_year.cpp"  # Specify the source file path
        target_repos=("mhd8a/Demo2" "mhd8a/Demo3")  # Add target repositories

        for repo in "${target_repos[@]}"; do
          echo "Checking file in $repo"
          git config user.email "mohammed.abdullah@in.bosch.com"
          git config user.name "Mohammed"
          git clone https://github.com/$repo.git
          cd $(basename $repo)

          # Check if the file exists in the target repository
          if [ -f "$source_file" ]; then
            echo "File $source_file already exists in $repo."
          else
            echo "File $source_file does not exist in $repo. Copying..."
            cp ../$source_file .

            # Stage, commit, and push the changes
            git add .
            git commit -m "Copy $source_file from source repo"
            git push origin main  # Adjust the branch name if necessary

            echo "File $source_file copied to $repo."
          fi

          cd ..
          rm -rf $(basename $repo)
        done
