name: Copy File to Target Repositories

on:
  workflow_dispatch:  # You can trigger this workflow manually

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: mhd8a/git-demo  # Replace with the source repository information

    - name: List files in source repo
      run: |
        source_file="new_year.cpp"  # Specify the source file path
        if [ -f "$source_file" ]; then
          echo "Source file $source_file exists."
        else
          echo "Source file $source_file does not exist."
          exit 1
        fi

    - name: Check and copy to target repos
      run: |
        source_file="new_year.cpp"  # Specify the source file path
        target_repos=("mhd8a/Demo2" "mhd8a/Demo3")  # Add target repositories
        pat_token="${{ secrets.Token_API_Acces }}"  # Replace with your PAT secret

        for repo in "${target_repos[@]}"; do
          echo "Checking file in $repo"

          # Check if the file exists in the target repository using the GitHub API
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $pat_token" "https://api.github.com/repos/$repo/contents/$source_file")

          if [ "$response" -eq "200" ]; then
            echo "File $source_file already exists in $repo."
          else
            echo "File $source_file does not exist in $repo. Copying..."

            # Get the source file's content
            source_file_content=$(base64 -w 0 "$source_file")

            # Create a JSON request body
            request_body=$(jq -n --arg message "Copy $source_file" --arg content "$source_file_content" --arg branch "main" '{"message": $message, "content": $content, "branch": $branch}')

            # Use the GitHub API to create or update the file
            curl -X PUT -H "Authorization: token $pat_token" -d "$request_body" "https://api.github.com/repos/$repo/contents/$source_file"

            echo "File $source_file copied to $repo."
          fi
        done
      env:
        Token_API_Acces: ${{ secrets.Token_API_Acces }}
