name: Copy File to Target Repositories

on:
  workflow_dispatch:  # Trigger the workflow manually
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  check_and_copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: mhd8a/git-demo  # Replace with the source repository information
        ref: main  # Adjust the branch name as needed

    - name: Set up Git with PAT
      run: |
        git config --global credential.helper store
        git config --global user.email "mohammedabdullah48@hotmail.com"
        git config --global user.name "mhd8a"
        echo "https://${{ secrets.Access_PAT }}@github.com" > remote_url
        git remote set-url origin "$(cat remote_url)"
      env:
        Access_PAT: ${{ secrets.Access_PAT }}

    - name: Set Git identity
      run: |
        git config --global user.email "mohammedabdullah48@hotmail.com"
        git config --global user.name "mhd8a"

    - name: List files in source repo
      run: |
        source_file="new_year.cpp"  # Specify the source file path
        if [ -f "$source_file" ]; then
          echo "Source file $source_file exists."
        else
          echo "Source file $source_file does not exist."
          exit 1
        fi

    - name: Check and copy to target repos
      run: |
        source_file="new_year.cpp"  # Specify the source file path
        target_repos=("mhd8a/Demo2" "mhd8a/Demo3")  # Add target repositories

        for repo in "${target_repos[@]}"; do
          echo "Checking file in $repo"
          response=$(curl -s -o /dev/null -
