name: Copy File to Target Repositories

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: mhd8a/git-demo
        ref: main  # Replace with the branch name as needed

    - name: List files in source repo
      run: |
        source_file="new_year.cpp"  # Specify the source file path
        if [ -f "$source_file" ]; then
          echo "Source file $source_file exists."
        else
          echo "Source file $source_file does not exist."
          exit 1
        fi

    - name: Copy file to target repositories
      run: |
        source_file="new_year.cpp"  # Specify the source file path
        target_repos=("mhd8a/Demo2" "mhd8a/Demo3")  # Add target repositories

        for repo in "${target_repos[@]}"; do
          echo "Copying file to $repo"

          # Read the source file contents
          file_contents="$(base64 -w0 "$source_file")"

         # Create a new file in the target repository using GitHub API
          response=$(curl -s -X PUT -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -d '{
              "message": "Add missing file",
              "content": "'"$file_contents"'"
            }' "https://api.github.com/repos/$repo/contents/path/to/source/file.ext")

          echo "File $source_file copied to $repo."
        done
